### ISSUE TITLE
Author value in card JSON

### ISSUE THREAD

**Issue by nfoert** [nfoert/cardie#15]
The `/card` page expects an author value in the JSON to display that information. Add it to be saved in the editor page

**Comment by vasnt** [comment]
Can you list down steps how to resolve this? i am in

**Comment by nfoert** [comment]
@vasnt, this will involve adding a new author value to the JSON in the [`editor_create_json`](https://github.com/nfoert/cardie/blob/e8ee760fe78691085959923609be56b9a70bf4dd/cardie/static/main/scripts/editor/editor_information.js#L129) function. This will be set to the creator of the card's username and will make the author value visible on the `/card` page.

**Comment by nfoert** [comment]
Done in 0.0.6-alpha
