### ISSUE TITLE
Last edited and created stats for card in the model

### ISSUE THREAD

**Issue by nfoert** [nfoert/cardie#30]
Have the info for when the card was created and last edited stored

**Comment by vasnt** [comment]
Let me know how to do it, i ll try my best.
if possible, specify/elaborate each step in detail

**Comment by nfoert** [comment]
Hi @vasnt, sure I can try to explain the steps! Thanks for being interested in contributing.

Most of the work is going to be done in the main `models.py` file, looking at the `Card` class. You'll want to create two new `models.DateTimeField` (set `blank=False` on the models), one for when the card is first created, and one for when the card was last edited. Then, in the main `views.py` file, under the function `create_card`. You'll find where you're creating the card on this line.
https://github.com/nfoert/cardie/blob/e8ee760fe78691085959923609be56b9a70bf4dd/cardie/main/views.py#L107
In the parameters of the new object, set the two new models to `timezone.now()`. Finally, in the `save_card` function in the same file, update the last saved model time to `timezone.now()` as well.

Hopefully this helps! Do let me know if you have any other questions.

**Comment by nfoert** [comment]
Done in v0.0.5-alpha
