### ISSUE TITLE
The logo in the readme is white on white

### ISSUE THREAD

**Issue by grishka** [nfoert/cardie#31]
![Снимок экрана 2024-08-01 в 02 07 24](https://github.com/user-attachments/assets/b3394dda-d0f2-46ab-a8d1-5d34ddf4ec81)

¯\\\_(ツ)_/¯

**Comment by nfoert** [comment]
Oh yeah, that's an oversight, I'm an always dark mode user so I never thought of that

**Comment by nfoert** [comment]
Fixed in v0.0.4-alpha
