### ISSUE TITLE
More card customizations

### ISSUE THREAD

**Issue by nfoert** [nfoert/cardie#39]
Lots of new features to make cards more unique
- [x] Background color
- [x] Secondary color
- [x] Collapse links if they don't all fit on the card
- [x] Rename `pronouns` and `username` in the editor page to something more versatile
- [x] Add info hovers to everything with examples
- [x] #28 
- [x] More Fonts
    - [ ] What happens if a font style gets deleted from the list?
    - [x] Create Wiki page for how to contribute new font styles
    - This could be a series of different font styles, eg,"basic", "modern", "fancy"
    - This could also be made so additional styles can be added easily, maybe users could suggest new styles
- [x] Make layout functional

**Comment by nfoert** [comment]
Done in `v0.0.7-alpha`

**Comment by Vineet8800** [comment]
@nfoert I would suggest we build something like this https://gw-card-builder.web.app/
