### ISSUE TITLE
Enhance UX: Change cursor to pointer on hover for buttons

### ISSUE THREAD

**Issue by VanshChitransh** [nfoert/cardie#53]
### Description:
The hover effect for the buttons on the homepage (`Try Cardie`, `Source Code`, and `Sign In`) does not currently show a pointer cursor. This can be improved by changing the cursor style to `pointer` when hovering over these interactive elements.

### Steps to Reproduce:
1. Go to the homepage.
2. Hover over the buttons (`Try Cardie`, `Source Code`, `Sign In`).
3. Notice that the cursor remains as the default cursor, indicating no interactive action.

###ScreenShot:
![Screenshot from 2024-10-02 01-00-10](https://github.com/user-attachments/assets/50348b86-86d2-45d2-b189-14f7fae702a8)

### Expected Behavior:
The cursor should change to a pointer when hovering over these buttons to indicate interactivity.

### Suggested Solution:
In the CSS, add the following rule for the buttons:

**Comment by VanshChitransh** [comment]
@nfoert I would love to work on this issue?

**Comment by nfoert** [comment]
This could be a good addition, feel free to complete this!

**Comment by Vineet8800** [comment]
Hi @nfoert, I would like to contribute to this update. Please add me to assignee.

**Comment by nfoert** [comment]
> Hi @nfoert, I would like to contribute to this update. Please add me to assignee.

@VanshChitransh posted this originally so they're assigned to it for now, I'm just trying to be fair :)
If they decide to no longer work on this issue I will assign it to you instead.

**Comment by Vineet8800** [comment]
Sure @nfoert, I understand that. Thank you for the reply.

**Comment by VanshChitransh** [comment]
@nfoert Please assign this issue to @Vineet8800

**Comment by nfoert** [comment]
Okay @VanshChitransh, it's @Vineet8800's now!

**Comment by nfoert** [comment]
Done in `v0.0.7-alpha`
