### ISSUE TITLE
Add Footer to the Bottom of the Website

### ISSUE THREAD

**Issue by VanshChitransh** [nfoert/cardie#54]
### Description:
I propose adding a footer at the bottom of the website. The footer can contain links to important resources such as:

- Contact Information
- Terms and Privacy Policy
- Social Media Links (if applicable)
- Copyright Information

### Benefits:
- Enhance navigation by providing easy access to key pages and resources.
- Improve the overall user experience by making the site feel more complete and polished.
- A footer can help with SEO by providing consistent links across all pages.

### Suggested Implementation:
The footer could be designed to be visually consistent with the current website's theme. It should include key links such as contact information, terms of service, and privacy policy, while being responsive across different devices.

### Additional Notes:
Further customizations can be made to match the website's branding. We can discuss what specific content to include in the footer.

**Comment by VanshChitransh** [comment]
@nfoert I would like to work on this issue.

**Comment by nfoert** [comment]
Hi there, there's already a footer on the bottom of the page, the icons must be pressed to expand the menus.
![image](https://github.com/user-attachments/assets/7276b4db-0c17-48c7-865b-b398eae73e99)
Thank you!
