### ISSUE TITLE
Remove Useless Warning Symbol from Webpage UI

### ISSUE THREAD

**Issue by VanshChitransh** [nfoert/cardie#56]
#### Description:
A useless symbol is appearing on the webpage, which could potentially confuse or mislead users. The symbol looks like a warning icon (triangle with an exclamation mark). This symbol does not serve any apparent purpose and can cause unnecessary concern for users navigating the site.

#### Steps to Reproduce:
1. Visit the webpage where the symbol is present.
2. Observe the useless warning symbol in the top-left corner of the UI (as shown in the attached screenshot).

#### Expected Behavior:
The symbol should be removed or replaced with an appropriate one that matches the context. If it's necessary to have an indicator, it should reflect a useful function.

#### Actual Behavior:
The useless warning symbol currently exists on the page, potentially confusing users unnecessarily.

#### Screenshot:
![Screenshot from 2024-10-02 01-17-18](https://github.com/user-attachments/assets/e6b00275-4ebe-4eed-bf60-4768bee55cf8)

#### Priority:
High

#### Suggested Solution:
- Investigate the source of the symbol and remove it if it's unnecessary.
- If the symbol serves a purpose, replace it with an icon that accurately reflects its function (e.g., an information icon if it's meant to provide additional details).

#### Additional Information:
- **Browser/OS:** [List of browsers/operating systems where the issue was observed]
- **Version:** [Version of the application or website]

**Comment by VanshChitransh** [comment]
@nfoert I would like to work on this issue.

**Comment by spline2hg** [comment]
i too had the same idea, but the first one is for notifying that the project is in development stage and can have bugs

**Comment by nfoert** [comment]
Hello @VanshChitransh, these icons can be pressed to open a footer menu with links to useful locations and a warning that the project is under active development.
![image](https://github.com/user-attachments/assets/7eba326a-ed68-4d03-81ff-deda80be6548)
