### ISSUE TITLE
Implement 'Back to Home' Button on Sign-in Page

### ISSUE THREAD

**Issue by VanshChitransh** [nfoert/cardie#58]
#### Description:
Add a "Back to Home" button on the sign-in page, allowing users to easily return to the homepage without needing to use the browser’s back functionality. This will improve the user experience by providing a clear and intuitive way to navigate back to the home page from the sign-in screen.

#### Benefits:
- Improved user navigation by offering an easy way to return to the home page.
- Reduced reliance on browser back buttons, creating a smoother and more intuitive user flow.
- Enhanced user experience, especially for those who land on the sign-in page by mistake or wish to explore more of the site before signing in.

#### Proposed Solution:
1. **UI Update:**
   - Add a "Back to Home" button on the sign-in page, positioned near the bottom or top of the page for easy visibility.
   - Ensure the button's design is consistent with the rest of the UI and clearly indicates its purpose.

2. **Functionality:**
   - The button should link back to the home page (`/`).
   - Ensure proper redirection from the sign-in page to the home page without any issues.

3. **Testing:**
   - Verify that the button works correctly across different devices and screen sizes.
   - Ensure that users are redirected to the home page upon clicking the "Back to Home" button.

#### Screenshot:
![Screenshot from 2024-10-02 01-34-04](https://github.com/user-attachments/assets/4ee844ba-676c-4d99-a243-ad8b58bac25b)

#### Priority:
Low to Medium

#### Dependencies:
- **Frontend update** to the sign-in page.
- **Routing configuration** to ensure proper redirection to the home page.

#### Additional Information:
- Ensure that the "Back to Home" button is prominent enough to be easily noticed but does not clutter the UI.

**Comment by VanshChitransh** [comment]
@nfoert i would be happy to take this issue.

**Comment by nfoert** [comment]
@VanshChitransh this feature is already implemented, you can press the Cardie logo to return to the index page.
