### ISSUE TITLE
Adding some icons to the icons option

### ISSUE THREAD

**Issue by ayush-848** [nfoert/cardie#62]
![image](https://github.com/user-attachments/assets/fd3edbb7-4cb2-4f9f-aec8-233448a56240)

**Comment by kevicebryan** [comment]
may i know how you'd like the icons to be stored, in a static way or from a db?

**Comment by ayush-848** [comment]
> may i know how you'd like the icons to be stored, in a static way or from a db?

I think a static way will be better than creating a new db

**Comment by nfoert** [comment]
Hello! There are icons here, it's just been broken on the production server (#21). This has potentially been fixed in #52, but it's not been tested yet. Thank you!
