### ISSUE TITLE
Background Blur doesn't hide correctly

### ISSUE THREAD

**Issue by nfoert** [nfoert/cardie#9]
The background blur that appears when opening dialog boxes (rename and icon selector) does not smoothly fade out when hiding.

**Comment by vasnt** [comment]
Can you list down steps how to resolve this? i am in

**Comment by nfoert** [comment]
@vasnt. I am not super sure on how to resolve this issue, it's something that I've not worked on figuring out. It will involve [`background_blur.js`](https://github.com/nfoert/cardie/blob/main/cardie/static/main/scripts/global/background_blur.js) and the background blur css at the bottom of [`ui.css`](https://github.com/nfoert/cardie/blob/e8ee760fe78691085959923609be56b9a70bf4dd/cardie/static/main/ui.css#L485), you'll have to do some experimenting to resolve the issue

**Comment by nfoert** [comment]
Done in v0.0.5-alpha
