### ISSUE TITLE
Add footer in `/Home`

### ISSUE THREAD

**Issue by iamDyeus** [nfoert/cardie#92]
Add a footer to the Homepage. It should include links to key sections like src, Report and Privacy Policy. The design should match the overall theme of the site and be responsive.

The footer could also include social media icons and wiki, GitHub redirects. If possible, a simple yet modern design would be preferred.

**Comment by nfoert** [comment]
Hello, there is already a footer on the `/home` page, it's expanded by clicking the icons in the bottom of the screen
![image](https://github.com/user-attachments/assets/d8315350-11f3-49fe-9c3f-68aa920f2d30)
